name: qaul_components
description: Shared UI components, breakpoints, and design tokens for qaul.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  badges: ^3.1.2
  flutter_riverpod: ^3.2.0
  flutter_svg: ^2.2.3
  qaul_ui:
    path: ../..
  shared_preferences: ^2.5.4
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  widgetbook_generator: ^3.7.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
