[package]
name = "qauld-ctl"
version = "2.0.0-rc.5"
authors = ["qaul community <contact@qaul.net>"]
edition = "2021"
description = "qaul-ctl: Client to control the qauld daemon"
license = "AGPL-3.0"
readme = "README.md"
homepage = "https://qaul.net"
repository = "https://github.com/qaul/qaul.net"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libqaul = { path = "../../libqaul" }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
log = "0.4"
pretty_env_logger = "0.5"
prost = "0.14"
clap = { version = "4.5", features = ["derive", "env"]}
tokio-util = { version = "0.7.18", features = ["codec"] }
uuid = { version = "1.13", features = ["v4"] }
