stages:
  - test
  - build
  - publish

# Build the Rust root on a pinned stable
build:
  image: rust:1.42.0-buster
  script:
    - cargo test --job 1
    - cargo build

# Run test suite
test_emberweb:
  stage: test
  image: circleci/node:12-browsers
  cache:
    key: yarn
    paths:
      - emberweb/.yarn
  script:
    - cd emberweb
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn run test
    - yarn run lint:hbs
    - yarn run lint:js

build_emberweb:
  stage: build
  image: node:12
  cache:
    key: yarn
    paths:
      - emberweb/.yarn
  script:
    - cd emberweb
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn run build --prod
  artifacts:
    paths:
      - webgui/dist/
