[workspace]
members = [

    # qaul.net service library
    "libqaul",

    # libqaul additions
    "libqaul/http-api",
    "libqaul/ipc",

    # qaul.net main services
    "libqaul/service/messaging",
    "libqaul/service/files",

    # decentralised routing protocol
    "ratman",
    "ratman/identity",
    "ratman/netmod",

    # A high-level network simulator
    # "service-sim",
    "visn",
    "permute",

    # Available netmod drivers
    "netmod-mem",
    "netmod-udp",

    # Client specific targets
    "clients/linux",
    "clients/linux-cli",
    "clients/http-test"
]
