[workspace]
members = [

    # qaul.net service library
    "libqaul",
    "libqaul/platform",
    "libqaul/storage",
	"libqaul/http-api",

    # qaul.net main services
    "libqaul/service/messaging",
    "libqaul/service/files",
    "libqaul/service/core",

    # decentralised routing protocol
    "ratman",
    "ratman/identity",
    "ratman/netmod",

    # A high-level network simulator
    "service-sim",
    "visn",

    # A _low level_ network simulator
    "netmod-sim",

    # Client specific targets
    "clients/linux",
    "clients/linux-cli"
]
