[package]
name = "qaul-files"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
qaul = { path = "../../", package = "libqaul" }
identity = { path = "../../../ratman/identity", package = "ratman-identity" }
mime = "0.3"
