name: qaul_rpc
description: RPC Connection between the Flutter app & qaul-rpc.
version: 0.0.1

publish_to: 'none'

flutter:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0
  logging: ^1.0.2

  ffi: ^2.0.1
  fixnum: ^1.0.1
  convert: ^3.0.1
  meta: ^1.7.0
  protobuf: ^2.0.0

  uuid: ^3.0.6
  rxdart: ^0.27.3
  equatable: ^2.0.3
  fast_base58: ^0.2.1
  hooks_riverpod: ^1.0.3
  utils: { 'path': '../utils' }
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
