name: qaul_rpc
description: RPC Connection between the Flutter app & qaul-rpc.
version: 0.0.1

publish_to: "none"

flutter:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: 1.18.0
  logging: 1.2.0

  ffi: 2.0.2
  fixnum: 1.1.0
  convert: 3.1.1
  meta: 1.10.0
  protobuf: 2.1.0

  uuid: 3.0.7
  rxdart: 0.27.7
  equatable: 2.0.5
  fast_base58: 0.2.1
  hooks_riverpod: 1.0.4
  utils: { "path": "../utils" }

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3
