[package]
name = "qaul_info"
edition = "2021"
description = "qaul.net routing-info protocol for libp2p"
version = "0.1.0"
authors = ["qaul.net community <contact@qaul.net>"]
license = "AGPL"

[dependencies]
libp2p = "0.47.0"
cuckoofilter = "0.5.0"
fnv = "1.0"
futures = "0.3.21"
log = "0.4"
rand = "0.8.4"
smallvec = "1.8.0"
