[package]
name = "ratman"
description = "A fully delay tolerant, decentralised userspace routing protocol"
license = "AGPL-3.0"
version = "0.0.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]

# Sub-components
identity = { path = "identity", package = "ratman-identity" }
netmod = { path = "netmod", package = "ratman-netmod"}
