[workspace]
resolver = "2"
members = [
    # qaul library
    "libqaul",

    # binaries
    "clients/cli",
    "clients/qauld",

    # libp2p modules
    "libp2p_modules/qaul_info",
    "libp2p_modules/qaul_messaging"
]