[workspace]
members = [
    # qaul library
    "libqaul",

    # ble module
    "ble_module",

    # binaries
    "clients/cli",
    "clients/qauld",

    # libp2p modules
    "libp2p_modules/qaul_info",
    "libp2p_modules/qaul_messaging"
]
