[package]
name = "ble_module"
version = "0.2.0"
authors = ["qaul community <contact@qaul.net>"]
edition = "2021"
license = "AGPL"

[dependencies]
async-trait = "0.1"
bluer = { version = "0.17", features = ["full"] }
bytes = "1.11"
crossbeam-channel = "0.5"
filetime = "0.2"
futures = "0.3"
futures-concurrency = "7.7"
lazy_static = "1.4"
log = "0.4"
prost = "0.14"
rand = "0.10"
serde = "1.0"
serde_json = "1.0"
simplelog = "0.12"
state = "0.6"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

# internal references
qaul-proto = { path = "../qaul-proto" }
