[package]
name = "qaul-cli"
version = "2.0.0-beta.17"
authors = ["qaul community <contact@qaul.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libqaul = { path = "../../libqaul" }
async-std = { version = "1.12.0", features = ["attributes"] }
futures = "0.3.29"
log = "0.4.20"
pretty_env_logger = "0.5.0"
prost = "0.12.3"
futures-ticker = "0.0.3"
state = "0.6.0"
bs58 = "0.5.0"
serde = {version = "1.0.193", features = ["derive"] }
uuid = { version = "1.6.1", features = ["v4"] }
