[package]
name = "qaul-cli"
version = "2.0.0-rc.1"
authors = ["qaul community <contact@qaul.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libqaul = { path = "../../libqaul" }
async-std = { version = "1.13", features = ["attributes"] }
futures = "0.3"
log = "0.4"
pretty_env_logger = "0.5"
prost = "0.13"
futures-ticker = "0.0.3"
state = "0.6"
bs58 = "0.5"
serde = {version = "1.0", features = ["derive"] }
uuid = { version = "1.11", features = ["v4"] }
