[package]
name = "qaul-cli"
version = "2.0.0-rc.5"
authors = ["qaul community <contact@qaul.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libqaul = { path = "../../libqaul" }
qaul-proto = { path = "../../qaul-proto" }
tokio = { version = "1", features = ["full", "io-std"] }
futures = "0.3"
log = "0.4"
pretty_env_logger = "0.5"
prost = "0.14"
futures-ticker = "0.0.3"
state = "0.6"
bs58 = "0.5"
serde = {version = "1.0", features = ["derive"] }
uuid = { version = "1.13", features = ["v4"] }
serde_json = "1.0.140"
rand = "0.9.2"
argon2 = "0.5.3"