[package]
name = "qaul-cli"
version = "0.2.0"
authors = ["qaul.net community <contact@qaul.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libqaul = { path = "../../libqaul" }
async-std = { version = "1.10.0", features = ["attributes"] }
futures = "0.3.21"
log = "0.4"
pretty_env_logger = "0.4"
prost = "0.9.0"
futures-ticker = "0.0.1"
state = "0.5"
bs58 = "0.4"
serde = {version = "=1.0", features = ["derive"] }
