[package]
name = "libqaul"
description = "Abstraction for building services over internet independent networks"
version = "0.1.0"
authors = [ "Katharina Fey <kookie@spacekookie.de>"]
license = "AGPL-3.0"
edition = "2018"

[dependencies]
alexandria = { version = "0.2", path = "../alexandria" }
netmod-mem = { path = "../netmod-mem", optional = true }
ratman = { path = "../ratman" }

async-std = { version = "=1.5", features = ["attributes", "unstable"] }
base64 = "0.10"
bincode = "1.0"
blake2 = "0.8"
crossbeam-channel = "0.4"
futures = "0.3"
hex = "0.4"
jni = { version = "0.14", optional = true, default-features = false }
mime = "0.3"
rand = "0.7"
serde = { version = "1.0", features = [ "derive" ] }
sodiumoxide = "0.2.5"
tempfile = { version = "3.0", optional = true }
tracing = "0.1"
tracing-futures = "0.2"

[dev-dependencies]
ratman-harness = { path = "../ratman/harness" }
serde_json = "1.0"
tempfile = "3.0"

[features]
default = ["generate-message", "testing"]
generate-message = []
testing = ["tempfile", "netmod-mem"]
ffi-java = ["jni"]

