[package]
name = "qaul-matrix-bridge"
version = "2.0.0-beta.15"
authors = ["qaul community <contact@qaul.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libqaul = { path = "../../libqaul" }
async-std = { version = "1.12.0", features = ["attributes"] }
futures = "0.3.21"
log = "0.4"
pretty_env_logger = "0.4"
prost = "0.11.0"
futures-ticker = "0.0.2"
state = "0.5"
bs58 = "0.4"
serde = { version = "=1.0", features = ["derive"] }
uuid = { version = "1.1.2", features = ["v4", "serde"] }
matrix-sdk = "0.4.0"
url = "2.3.1"
tokio = { version = "1.28.2", default-features = false, features = [
    "rt-multi-thread",
    "macros",
] }
dirs = "5.0.1"
config = "0.13.3"
serde_yaml = "0.9.22"
libp2p = "0.50.0"
mime = "0.3.17"
