name: utils
description: A new Flutter package project.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fixnum: ^1.1.0
  intl: ^0.20.2
  image: ^4.1.3
  mime: ^2.0.0
  path_provider: ^2.0.15
  timeago: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter: